baseURL = '/'
languageCode = 'en-us'
title = 'LONGO LAND'

[markup.goldmark.renderer]
unsafe = true
hardWraps = false

[taxonomies]
tag = "tags"


[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
  showTwitter = true